### ISSUE TITLE
Matriz de Rastreabilidade de US

### ISSUE THREAD

**Issue by wparaujo** [fga-eps-mds/2018.2-Integra-Vendas#133]
A matriz de rastreabilidade será útil para determinar quais issues representam valor a nível de épico. E também reconhecer o status do épico, e quais issues precisam ser realizadas para ser completado.

Tarefas
- [ ] Criar épicos faltantes
- [ ] Desenhar matriz 
- [ ] Documentar no git pages

**Comment by lucasca73** [comment]
@wparaujo e @lugope como esta o status dessa issue?

**Comment by lugope** [comment]
Não coube no escopo do projeto.
