### ISSUE TITLE
TS05

### ISSUE THREAD

**Issue by ricardocanela** [fga-eps-mds/2018.2-Integra-Vendas#143]
**Descrição**
Eu, como **desenvolvedor**, desejo que **seja feito um end point no login microservice para dar um get em um usuário pelo id** para **completar funcionalidades de outros microservices que requerem informações dos usuários**.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Usuário deverá ser solicitado por id;
- Deverá retornar todos os dados do usuário;

**Comment by lucasca73** [comment]
@ricardocanela pode verificar o status dessa issue ?
