### ISSUE TITLE
Definir tecnologia de CND

### ISSUE THREAD

**Issue by ricardocanela** [fga-eps-mds/2018.2-Integra-Vendas#218]
Estudar algumas opções para o armazenamento de imagens da nossa aplicação, informar o time de desenvolvimento e disponibilizar um exemplo / tutorial para implementação.

**Tarefas**
- [x] Analizar AWS;
- [x] Analizar DigitalOcean;
- [x] Analizar Cloudnary.

**Comment by lucasca73** [comment]
@ricardocanela poderia pontuar essa issue por favor?
