### ISSUE TITLE
Definir tecnologia de notificação

### ISSUE THREAD

**Issue by ricardocanela** [fga-eps-mds/2018.2-Integra-Vendas#219]
Nosso aplicativo irá utilizar sistema de notificação, para isso, utilizaremos a tecnologia Expo Push Notifications.

Alguns detalhes de implementação se encontram no documento de arquitetura.

O link de instrução para desenvolvimento é esse: 
https://docs.expo.io/versions/latest/guides/push-notifications

Em caso de dúvida na implementação, nossos colegas do CarDefense estão utilizando essa tecnologia, por isso esses links podem ser uteis:
https://fga-eps-mds.github.io/2018.2-CarDefense/docs/docarquitetura.html
https://github.com/CarDefense/CarDefense_Notification

**Comment by lucasca73** [comment]
@ricardocanela por favor, poderia pontuar essa issue?
