### ISSUE TITLE
TS10 - Cobertura de Testes da api-gateway

### ISSUE THREAD

**Issue by lucasca73** [fga-eps-mds/2018.2-Integra-Vendas#226]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***aumentar a cobertura de testes da api-gateway*** para ***aumentar a qualidade do projeto***.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- 80% de cobertura de testes no mínimo;
- Testes de todas as rotas.

**Tarefas**
- [x] Realizar testes unitário nas funções da api-gateway;

**Comment by lugope** [comment]
O PR será feito hoje.
