### ISSUE TITLE
TS11 - Testes de Login para Frontend

### ISSUE THREAD

**Issue by lucasca73** [fga-eps-mds/2018.2-Integra-Vendas#227]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***testar o sistema de login*** para ***aumentar a garantia que a funcionalidade esteja funcionando de acordo com o esperado***.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Cadastrar novo usuário;
- Logar com o usuário cadastrado;
- Chegar a tela inicial do app.

**Tarefas**
- [x] Testar cadastro do usuário;
- [x] Testar login com usuário já cadastrado;
- [x] Testar a passagem da tela de login para a tela inicial do app.

**Comment by andrelucax** [comment]
O teste de cadastro de produto e login com usuario cadastrado ja sao testados no backend... Creio no front so precisa ser testado se a funcao foi chamada (no caso de teste unitario)...

**Comment by wparaujo** [comment]
Devido a dúvidas quanto ao funcionamento dos testes e ter componentes das telas testados, será marcado um treinamento para testes do react native.
