### ISSUE TITLE
TS12 - Testes de produto para o frontend

### ISSUE THREAD

**Issue by lucasca73** [fga-eps-mds/2018.2-Integra-Vendas#228]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***testar o sistema de produtos*** para ***aumentar a qualidade do software***.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Deve haver pelo menos 80% de cobertura de testes em cada arquivo relacionado com a funcionalidade;
- Os principais arquivos que devem ser testados são: Create product; My products; My products details; OffersDetails; Offers;

**Tarefas**
- [x] Testar o Create product;
- [x] Testar o My product;
- [x] Testar o Products details;
- [x] Testar o OffersDetails;
- [x] Testar o Offers;

**Comment by lugope** [comment]
Virou dívida técnica da sprint 10.

**Comment by lugope** [comment]
Virou dívida técnica da sprint 11.

**Comment by lucasca73** [comment]
Pesquisando encontrei um [artigo](https://medium.com/react-native-training/learning-to-test-react-native-with-jest-part-4-1d6df49866b1) no medium, que referencia outros dois artigos para uso de test e fetch.
* [Artigo I](https://medium.com/@ferrannp/unit-testing-with-jest-redux-async-actions-fetch-9054ca28cdcd)
* [Artigo II](https://blog.callstack.io/unit-testing-react-native-with-the-new-jest-ii-redux-snapshots-for-your-actions-and-reducers-8559f6f8050b)

**Comment by shayanealcantara** [comment]
Devido a pouco tempo, o arquivo MyProductDetails não pode ser testado nessa sprint.

**Comment by lugope** [comment]
As atualizações a partir de agora são para a documentação do burndown da sprint 11

**Comment by lugope** [comment]
Coleta do burndow da sprint 11 feito. A documentação da issue voltou para seu estado original.
