### ISSUE TITLE
TS13 - Testar pedido no frontend

### ISSUE THREAD

**Issue by lucasca73** [fga-eps-mds/2018.2-Integra-Vendas#229]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***testar o sistema de pedidos*** para ***aumentar a qualidade do software***.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Deve haver pelo menos 80% de cobertura de testes em cada arquivo relacionado com a funcionalidade;
- Os principais arquivos que devem ser testados são: Order details; Ordered Products.

**Tarefas**
- [x] Testar o Order details;
- [x] Testar o Ordered Products.

**Comment by andrelucax** [comment]
![image](https://user-images.githubusercontent.com/42394759/48290528-593a9080-e45a-11e8-8657-3c04e97e8eff.png)

Estamos tendo dificuldade em simular o props.navigation, tentamos contornar de varias formar e nao foi possivel. Essa funcao do jeito que esta sera removida pois o token sera salvo no celular para manter o usuario logado

**Comment by lugope** [comment]
Virou dívida técnica da sprint 12
