### ISSUE TITLE
Exceções ao rodar testes na API-Gateway

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2018.2-Integra-Vendas#233]
**Describe the bug**
Na primeira tentativa de rodar os testes na API Gateway, utilizando o comando `make staging-integration-tests`, os testes são executados normalmente. Já a partir da segunda tentativa, algumas exceções são lançadas na tela: 
- ConnectionResetError: [Errno 104] Connection reset by peer E
- BrokenPipeError: [Errno 32] Broken pipe.

**To Reproduce**
1. Acessar o repositório clonado https://github.com/fga-eps-mds/2018.2-Integra-Vendas/ , na branch dev
2. Utilizar o comando `make staging-integration-tests`

**Expected behavior**
Espera-se a execução dos testes **sem erros causados pelas exceções.**

**Screenshots**
1º tentativa:
![image](https://user-images.githubusercontent.com/33501171/47468491-f4343900-d7d1-11e8-84d7-c0e40635d5ec.png)

A partir da 2º tentativa:
![image](https://user-images.githubusercontent.com/33501171/47468568-5a20c080-d7d2-11e8-8698-6bbf5b9ce98d.png)

![image](https://user-images.githubusercontent.com/33501171/47468908-73c30780-d7d4-11e8-987b-dd52f75af719.png)

![image](https://user-images.githubusercontent.com/33501171/47468932-8dfce580-d7d4-11e8-8f6c-2c6d30123ada.png)

**Desktop**
 - OS: [Tentativas no Ubuntu 16.04 e 18.04]

**Adicionais**
Este problema parece ter comportamentos aleatórios, visto que por 2 vezes seguidas, a partir da 2º tentativa, as exceções não foram lançadas.

**Comment by lucasca73** [comment]
Estou pesquisando aqui, e esses erros parecem ser referentes ao mesmo problema que é quando a conexão entre os serviços é fechada antes da mensagem terminar de ser enviada.... 
[stackoverflow broken-pipe-error](https://stackoverflow.com/questions/10253288/django-development-server-broken-pipe-error)

**Comment by lucasca73** [comment]
@shayanealcantara tem como você executar o 

```shell
make staging-integration-tests
```

na branch ```hotfix/integration-tests```

e mostrar o resultado aqui?

**Comment by shayanealcantara** [comment]
Certo, estou rodando agora na `branch hotfix/integration-tests`:

1º tentativa (sem fazer nenhuma alteração)
![image](https://user-images.githubusercontent.com/33501171/47475018-281e5700-d7f0-11e8-8569-ce9fe357a3ad.png)

2º tentativa (já com alterações)
![image](https://user-images.githubusercontent.com/33501171/47475381-7ed86080-d7f1-11e8-92f8-08508b6898a9.png)
![image](https://user-images.githubusercontent.com/33501171/47475436-b34c1c80-d7f1-11e8-9e76-fd01ea3a9ba5.png)

![image](https://user-images.githubusercontent.com/33501171/47475421-9dd6f280-d7f1-11e8-9e05-bac1dcca4c57.png)

**Comment by WelisonR** [comment]
Aparentemente, o erro está relacionado com a sincronia durante a inicialização dos microsseviços ao digitar o comando `sudo make staging-integration-tests`, devido que às vezes alguns microsserviços são carregados após a realização dos testes, conforme pode-se ver na imagem abaixo.

Microsserviço de _login_ é carregado após a realização dos testes:
![image](https://user-images.githubusercontent.com/31112450/47537568-d8e23000-d89c-11e8-9cb9-5abe1ff71875.png)

**Comment by lucasca73** [comment]
Acaba que também foi um erro que aconteceu no TravisCI. Então essa correção realmente foi muito bem vinda. 😄

**Comment by lucasca73** [comment]
<img src="https://user-images.githubusercontent.com/4529055/47540128-ef42b880-d8a9-11e8-8a1e-dd3521063219.png" width=500>
