### ISSUE TITLE
Atualizar EVM

### ISSUE THREAD

**Issue by lucasca73** [fga-eps-mds/2018.2-Integra-Vendas#237]
Coletar os dados referentes ao evm

**Tarefas**
- [x] Coletar os dados
- [x] Elaborar gráficos

**Comment by lugope** [comment]
O EVM foi finalizado por @lugope e @wparaujo e seus dados podem ser acessados clicando [aqui](https://docs.google.com/spreadsheets/d/1-9_IZAkohG6TObwngSHjI-Ua9gkoXecHn9dI-WMfIe8/edit?usp=sharing).
