### ISSUE TITLE
Atualizar Guia de Identidade Visual

### ISSUE THREAD

**Issue by wparaujo** [fga-eps-mds/2018.2-Integra-Vendas#238]
Criar adaptações da identidade visual de acordo com as novas histórias.

**Tarefas**
- [x] Atualizar Diagrama das Telas;
- [x] Atualizar a logo no GH pages

**Observações**
* A *issue* deve ser pontuada;
* A *issue* deve ser delegada a alguém;
* A *issue* deve ter *labels*;
* A *issue* deve pertencer a uma *milestone*.

**Comment by lugope** [comment]
Documento de identidade visual revisado.
