### ISSUE TITLE
Fazer deploy manual do FrontEnd

### ISSUE THREAD

**Issue by ricardocanela** [fga-eps-mds/2018.2-Integra-Vendas#240]
Gerar o apk da aplicação e subir na Google Play

**Tarefas**
- [x] Gerar apk à partir do expo;
- [ ] Subir o apk no Google Play;

**Comment by lucasca73** [comment]
Foi encontrado um erro inicialmente:
 solucionado corrigindo a referencia de uma variável.

Agora, um outro problema persiste. Labels não aparecem, e componentes não agem como esperado.
