### ISSUE TITLE
Fazer deploy continuo do FrontEnd

### ISSUE THREAD

**Issue by ricardocanela** [fga-eps-mds/2018.2-Integra-Vendas#250]
Criar pipeline de deploy continuo da aplicação para a Google Play

**Tarefas**
- [ ] Concluir issue #240 para gerar apk;
- [ ] Automatizar processo de gerar apk;
- [ ] Construir deploy contínuo na Google Play.

**Observações**
* A *issue* deve ser pontuada;
* A *issue* deve ser delegada a alguém;
* A *issue* deve ter *labels*;
* A *issue* deve pertencer a uma *milestone*.

**Comment by lucasca73** [comment]
Solucionado no PR fga-eps-mds/2018.2-FGAPP-FrontEnd#75
