### ISSUE TITLE
Atualizar Roadmap do Projeto

### ISSUE THREAD

**Issue by wparaujo** [fga-eps-mds/2018.2-Integra-Vendas#252]
Fazer a atualização do roadmap do projeto para a segunda release.

**Tarefas**
- [x] Elencar atividades do projeto por sprint;

**Observações**
* A *issue* deve ser pontuada;
* A *issue* deve ser delegada a alguém;
* A *issue* deve ter *labels*;
* A *issue* deve pertencer a uma *milestone*.

**Comment by lugope** [comment]
Resolvida pelo PR #302 .
