### ISSUE TITLE
Definição das milestones até a R2

### ISSUE THREAD

**Issue by lucasca73** [fga-eps-mds/2018.2-Integra-Vendas#253]
A fim de planejar melhor e separar atividades correspondentes para cada milestone. 

**Tarefas**
- [x] Documentar milestones em sprints até a R2

**Comment by lugope** [comment]
Acho que a atividade de separar as atividades pode ser quebrada em outra issue, pois ela é bem trabalhosa e vai ser tipo uma planning nossa.

E não se esqueça de pontuar a issue e definir sua milestone e responsáveis.

**Comment by lucasca73** [comment]
Verdade, podemos quebrar mesmo. Vou pontua-la tb 👍

**Comment by lucasca73** [comment]
Essa história foi quebrada para a #267
