### ISSUE TITLE
Colher métricas sobre commits

### ISSUE THREAD

**Issue by ricardocanela** [fga-eps-mds/2018.2-Integra-Vendas#256]
Fazer coleta e análise de métricas sobre commits

**Tarefas**
- [ ] Coletar métricas sobre commits;
- [ ] Documentar métricas coletadas;

**Observações**
* A *issue* deve ser pontuada;
* A *issue* deve ser delegada a alguém;
* A *issue* deve ter *labels*;
* A *issue* deve pertencer a uma *milestone*.

**Comment by lugope** [comment]
Não coube no escopo do projeto.
