### ISSUE TITLE
Links quebrados no TAP

### ISSUE THREAD

**Issue by leomedeiros1** [fga-eps-mds/2018.2-Integra-Vendas#258]
**Describe the bug**
Ao clicar no nome de alguém na página do TAP, o redirecionamento está sendo apontado para uma página de erro.

**To Reproduce**
1. Vá até o [TAP](https://fga-eps-mds.github.io/2018.2-Integra-Vendas/docs/tap)
2. Clique no nome de alguem [Lucas Costa](https://github.com/orgs/fga-eps-mds/people/lucasca73)
3. Veja o erro.

**Expected behavior**
Redirecionar para a página de perfil do usuário.

**Screenshots**
Tela a qual você é redirecionado:
![image](https://user-images.githubusercontent.com/42392744/47689195-96d02b80-dbc7-11e8-9fdb-e231fb7482c9.png)

**Desktop:**
 - OS: Ubuntu 16.4.5
 - Browser Mozilla Firefox.
 - Version 63.0

**Comment by lucasca73** [comment]
Realmente @leomedeiros1. E os nomes não deveriam estar redirecionando para o people do projeto. E sim para os perfis pessoais de cada um.
