### ISSUE TITLE
Transparência

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/2018.2-Integra-Vendas#260]
- [x] Atenção a documentaçao das sprints - a falta de documentacao up to date gera falta de transparecencia sobre o andamento das sprints, e dificulta bastante a gestão de risco do time!

- [x] Issues estão muito boas (tanto a claridade, a objetividade) - as conversas técnicas nas issues estao bem legais

- [x] PRs estao OK

- [x] Por que usar o travis para integraçao continua e o gitlabci para deploy continuo? poderiam usar a mesma ferramenta para fazer os dois - parecer ser um overhead

https://about.gitlab.com/devops-tools/travis-ci-vs-gitlab.html

- [x] Ambiente de homolog - lançar a versao beta do app no google play

- [x] Testes, testes e testes

- [x] ta acabando ;)

**Comment by lucasca73** [comment]
@RochaCarla O gitlab trabalha com uma interface muito mais amigável para o pipeline, e a publicação de imagens no docker hub é mais fácil. Nos microsserviços, o pipeline inteiro incluindo os testes estão no gitlab.

houve uma mudança recente para introdução de testes de integração no api-gateway que esta no repositório padrão [integra-vendas](https://github.com/fga-eps-mds/2018.2-Integra-Vendas). Ocorreu que para usar o docker-compose no gitlab é necessário configurações internas dos runners, seria necessário ter acesso ao runner, no travis o uso do docker-compose foi tranquilo, que levou a levar os testes para lá. Obrigado pelo feedback, irei atualizar a api-gateway completamente para o travis. #261

**Comment by lugope** [comment]
Feedbacks analisados e aplicados! Muito obrigado @RochaCarla !
