### ISSUE TITLE
TS14 - Testes de settings para o frontend

### ISSUE THREAD

**Issue by lucasca73** [fga-eps-mds/2018.2-Integra-Vendas#269]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***testar o sistema de settings*** para ***aumentar a qualidade do software***.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Deve haver pelo menos 80% de cobertura de testes em cada arquivo relacionado com a funcionalidade;
- Os principais arquivos que devem ser testados são: Settings e UserProfile.
- Refatorar o UserProfile.js para que o render não seja desnecessariamente grande. Mover o excesso de conteúdo dentro do render do UserProfile.js para o UserCard.js .

**Tarefas**
- [x] Refatorar o UserProfile para voltar a usar o UserCard;
- [x] Testar o screens/tab_navigator/settings/settings/Settings.js;
- [x] Testar o screens/tab_navigator/settings/settings/UserProfile.js;
- [x] Testar o screens/components/UserCard.js;

**Comment by lucasca73** [comment]
Essa história deve ser realizada após a aceitação do PR - fga-eps-mds/2018.2-FGAPP-FrontEnd#56

**Comment by juniopereirab** [comment]
Essa issue foi solucionada com o envio do [Pull Request #104](https://github.com/fga-eps-mds/2018.2-FGAPP-FrontEnd/pull/104).
