### ISSUE TITLE
TS16 - Aumentar a nota do Code Climate no repositório da API Gateway

### ISSUE THREAD

**Issue by lugope** [fga-eps-mds/2018.2-Integra-Vendas#284]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***refatorar o código no repositório do API Gateway*** para ***garantir a qualidade do código do produto*** .

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Resolver os *code smells* indicados pelo Code Climate;
- Resolver as duplicações indicadas pelo Code Climate;
- A nota de manutenibilidade do Code Climate no repositório da [API](https://github.com/fga-eps-mds/2018.2-Integra-Vendas) deve ser igual à A.

**Tarefas**
- [x] Resolver os *code smells*;
- [ ] Resolver as duplicações.

**Comment by andrelucax** [comment]
Realizado no PR https://github.com/fga-eps-mds/2018.2-Integra-Vendas/pull/289
