### ISSUE TITLE
TS17 - Aumentar a nota do Code Climate no repositório do Login

### ISSUE THREAD

**Issue by lucasca73** [fga-eps-mds/2018.2-Integra-Vendas#285]
**Descrição**
Eu, como ***desenvolvedor***, gostaria de ***refatorar o código no repositório do Login*** para ***garantir a qualidade do código do produto*** .

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Resolver os *code smells* indicados pelo Code Climate;
- Resolver as duplicações indicadas pelo Code Climate;
- A nota de manutenibilidade do Code Climate no repositório da [Login](https://codeclimate.com/github/fga-eps-mds/2018.2-FGAPP-login)

**Tarefas**
- [ ] Resolver os *code smells*;
- [ ] Resolver as duplicações.

**Comment by andrelucax** [comment]
Resolvido no PR https://github.com/fga-eps-mds/2018.2-FGAPP-login/pull/33
