### ISSUE TITLE
Atualizar documento de arquitetura

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/2018.2-Integra-Vendas#308]
**Descrição**
- Atualizar o documento de arquitetura conforme atual estrutura do projeto.

**Tarefas**
- [x] Revisar arquitetura.
- [x] Atualizar o documento de arquitetura baseado nas atuais estruturas do _front-end_, _api gateway_ e microsserviços.
- [x] Atualizar a imagem da subseção 2.1;
- [x] Atualizar a imagem da subseção 2.2;
- [x] Atualizar a imagem da subseção 4.1;
- [x] Atualizar a imagem da seção 4.2 (Front-End).

**Comment by shayanealcantara** [comment]
@ricardocanela, poderia revisar esse conteúdo e agregar valor caso seja necessário?

**Comment by ricardocanela** [comment]
@shayanealcantara olhei o doc e agora sim está nos conformes, obrigado por subir as imagens que te enviei :)
