### ISSUE TITLE
Login through other platforms

### ISSUE THREAD

**Issue by LuisCL94** [fga-eps-mds/2018.2-Integra-Vendas#336]
Proposal to log in using accounts from other platforms such as:

![jhwnz](https://user-images.githubusercontent.com/37872798/49772944-48d63980-fcd6-11e8-86c1-4cefaa34033d.png)

It would look great something like this...

**Comment by lucasca73** [comment]
Hi there! @LuisCL94, our sing in, sign up service is here [login microservice](https://github.com/fga-eps-mds/2018.2-FGAPP-login) do you mind to move this feature request to there? thanks

**Comment by LuisCL94** [comment]
Okay
