### ISSUE TITLE
Feedback Inicial - Issues e Documentação

### ISSUE THREAD

**Issue by fepas** [fga-eps-mds/2018.2-Integra-Vendas#57]
Olá pessoas! A Carla me pediu pra dar um feedback dos grupos, e aqui estou! 

# IFood

- ## *Issues*

#### **Comunicação**

Vocês estão não estão se comunicando muito bem nas *issues*.

Se comunicar pelas *issues* trás uma comunicação bem transparente do projeto de vocês, e ajuda na avaliação de como vocês estão lidando com as adversidades de cada *issue*. É bem interessante que informações importantes estejam sempre sendo discutidas nas *issues*, além das outras ferramentas de comunicação que vocês usam, como *Telegram*.

#### **Pontuação**

Vocês estão utilizando bem as pontuações nas *issues*, aqui tem alguns links pra ajudar vocês ainda mais nisso:

- Detalhes sobre o método *Planning Poker*:

    http://www.metodoagil.com/planning-poker/

- Site para realizar o *Planning Poker* online:

    https://scrumpoker.online/

Eu particularmente prefiro fazer com *post-its*, mas vai da preferência da necessidade de cada grupo.

#### **Nomes**

As *issues* estão com bons nomes. É interessante a prática de padronizar os nomes, e vocês já fazem utilizando os verbos no infinitivo (que já seria a minha recomendação). Acho que as US podiam ter alguma informação além do número no título, mas se vocês preferem se organizar assim, não tem problema.(◕‿◕✿)

#### ***Labels***

As Labels estão um pouco "pobres", mas é normal para essa primeira etapa do projeto. Provavelmente eu faça um mini-guia para ajudar grupos que estão mal nisso, e consequentemente vai ajudar vocês!.

As issues de vocês estão bem nomeadas, bem explicativas, parabéns! Só precisam melhorar um pouco na comunicação e nas labels.

- ## Documentação

#### **Documento de Visão**

O documento de visão de vocês está bem claro em mostrar o que é o problema, seus desdobramentos, e a forma de atuação do software nesse problema.
Cumpre a função, está bem organizado, escrito e detalhado.

#### **Documento de Arquitetura**

O documento de arquitetura bom no geral, os diagramas estão bem legais, principalmente o do react-native (eu vi isso ai viu ( ͡° ͜ʖ ͡°) ), nice!

#### **Documentação Geral**

O documento de arquitetura o de visão estão bons, mas não encontrei as documentações das sprints. É bem importante que essas documentações sejam feitas para garantir a transparência do projeto e a evolução de vocês!

- ## Considerações Finais

Vocês estão no caminho certo. Agora é só corrigir os erros que vai dar tudo certo. Uma dica que eu tenho pra vocês, é ver com a Carla se vocês podem definir um identidade visual própria, pra não ficar usando o nome IFood, atualizar o README com informações do projeto. ◕‿◕

A Carla vai poder dar um feedback mais técnico pra vocês, mas espero ter ajudado na melhoria do
projeto de vocês de alguma forma. ( ⌒o⌒)人(⌒-⌒ )

[]s, @fepas

**Comment by lugope** [comment]
Muito obrigado pelo feedback! Estamos trabalhando para resolver as considerações feitas.
Nós já fizemos alguns documentos que você citou no Google Docs e vamos transferir para o Git Pages. Vamos parar com essa prática pois vimos que isso está atrasando a entrega dos documentos para avaliação. Assim, vamos produzir direto no Pages.

**Comment by fepas** [comment]
@lugope É uma boa vocês fazerem direto no pages mesmo! Vocês também podem iniciar fazendo eles em *Markdown* e depois passar para o pages, é uma opção.

**Comment by lucasca73** [comment]
@fepas fizemos uma atualização nas labels recentemente, poderia nos dar o feedback referente a isso novamente? :D

**Comment by fepas** [comment]
@lucasca73 Vou dar uma olhada sim! Desculpa a demora, não tinha visto antes! hahahaha
